spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graph_test?useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: ${JDBC_PASS:123456}
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 15
      idle-timeout: 10000
  messages:
    cache-duration: 10
